---
- name: ansible-test
  hosts: GNS3
  connection: local
  
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      
  tasks:
#    - name:  snmp ACL
#      ios_config:
#        lines:
#          - 10 permit 192.168.2.0 0.0.0.255
#          - 20 deny any
#        parents: ip access-list standard 10
#        provider: "{{ cli }}"

#      register: output
    - name: snmp config
      ios_config:
        lines:
          - snmp-server host 192.168.2.1 version 2c traps
          - no snmp-server community readonly RO 10
          - snmp-server community readonly RO
        provider: "{{ cli }}"

      register: output
      
    - name: output
      debug:
        var: output #.stdout
