---
- name: ansible-test
  hosts: GNS3
  connection: local
  
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      
  tasks:
    - name: show version
      ios_command:
        commands: show version | i IOS | i Version 
        provider: "{{ cli }}"

      register: output
      
    - name: output
      debug:
        var: output.stdout
